#!/bin/sh

preselection='isoTight_1>0.5&&isoTight_2>0.5&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&'\
'againstMuonTight3_1>0&&againstMuonTight3_2>0&&'\
'againstElectronVLooseMVA6_1>0&&againstElectronVLooseMVA6_2>0&&'\
'npv>0&&diLeptons==0&&extraelec_veto==0&&extramuon_veto==0'

## Trigger Selection
trigselection='pt_1>24&&HLT_Any>0&&hltMedComb_1>0&&hltMedComb_2' # only for MC
trigselectiondata='HLT_Any>0' #only for Data 
signalselection='(pt_sv>100&&pt_sv<170)*(njets==1||(njets>=2&&!(mjj>300&&abs(jdeta)>2.5&&njetingap<1)))'

luminosity=35870 #pb
outputDir='diTauPlots_RDF'
mkdir $outputDir

folder='tt_inclusive'
direc='/hdfs/store/user/ojalvo/ztt_weighted_Apr7_svFit/'

verbose=1

MakeDataCardHThTh_2016_RDF channel='diTau'  folder=$folder  preselection=$preselection trigSelection=$trigselection signalSelection=$signalselection dir=$direc weight='__WEIGHT__*GENWEIGHT'  luminosity=$luminosity  variable='m_sv' bins=30 min=0 max=300 luminosity=$luminosity bins=30 min=2 max=302 outputFile=$outputDir'/tauTau_m_sv.root'
