#!/bin/sh

preselection='isoTight_1>0.5&&isoTight_2>0.5&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&'\
'againstMuonTight3_1>0&&againstMuonTight3_2>0&&'\
'againstElectronVLooseMVA6_1>0&&againstElectronVLooseMVA6_2>0&&'\
'npv>0&&diLeptons==0&&extraelec_veto==0&&extramuon_veto==0'

## Trigger Selection
trigSelection='pt_1>24&&HLT_Any>0&&hltMedComb_1>0&&hltMedComb_2' 
trigSelectionData='HLT_Any>0' #only for Data 

luminosity=35870 #pb
outputDir='diTauPlots_Boost'
mkdir $outputDir

verbose=1

folder='tt_inclusive'
direc='/hdfs/store/user/ojalvo/ztt_weighted_Apr7_svFit/'

MakeDataCardHThTh_2016_Boost channel='diTau'  folder=$folder  preselection=$preselection trigSelection=$trigSelection dir=$direc weight='__WEIGHT__*GENWEIGHT'  luminosity=$luminosity  variable='m_sv' bins=30 min=0 max=300 luminosity=$luminosity bins=30 min=2 max=302 outputFile=$outputDir'/tauTau_m_sv.root' verbose=$verbose
